using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Shared.DisplayTemplates
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Shared/DisplayTemplates/BinaryMeta.cshtml")]
    public partial class _Areas_Management_Views_Shared_DisplayTemplates_BinaryMeta_cshtml_ : System.Web.Mvc.WebViewPage<DD4T.ContentModel.BinaryMeta>
    {
        public _Areas_Management_Views_Shared_DisplayTemplates_BinaryMeta_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<tr>\r\n    <td>ID</td>\r\n    <td>");

            
            #line 4 "..\..\Areas\Management\Views\Shared\DisplayTemplates\BinaryMeta.cshtml"
   Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Variant ID</td>\r\n    <td>");

            
            #line 8 "..\..\Areas\Management\Views\Shared\DisplayTemplates\BinaryMeta.cshtml"
   Write(Model.VariantId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Last publish date</td>\r\n    <td>");

            
            #line 12 "..\..\Areas\Management\Views\Shared\DisplayTemplates\BinaryMeta.cshtml"
   Write(Model.LastPublishedDate);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n");

        }
    }
}
#pragma warning restore 1591
