using System.Linq;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Shared.DisplayTemplates
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Shared/DisplayTemplates/Page.cshtml")]
    public partial class _Areas_Management_Views_Shared_DisplayTemplates_Page_cshtml_ : System.Web.Mvc.WebViewPage<DD4T.ContentModel.Page>
    {
        public _Areas_Management_Views_Shared_DisplayTemplates_Page_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<tr>\r\n    <td>ID</td>\r\n    <td>");

            
            #line 5 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
   Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Title</td>\r\n    <td>");

            
            #line 9 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td># of component presentations</td>\r\n    <td>");

            
            #line 13 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
           
        if (Model.ComponentPresentations != null)
        {
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
       Write(Model.ComponentPresentations.Count());

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
                                                 
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <span>0</span>\r\n");

            
            #line 21 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n</tr>\r\n");

            
            #line 25 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
 if (Model.Schema != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>Metadata schema</td>\r\n        <td>");

            
            #line 29 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"
       Write(Model.Schema.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 31 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Page.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
