image: mcr.microsoft.com/dotnet/framework/sdk:4.8.1
clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly  
definitions:
  services:
    docker:
      memory: 4096
  caches:
    nuget: src/packages
  steps:
    - step: &build-packages
       name: Build all packages
       size: 2x
       script:
       - export PROJECT_NAME=Dyndle.Modules.Core
       - export AlphaLabel=`date +"%Y%m%d%H%M%S"`
       #- apt-get update 
       - nuget restore $BITBUCKET_CLONE_DIR/src/Dyndle.Modules.sln
       - msbuild /p:Configuration="Release" /p:Branch="$BITBUCKET_BRANCH" /p:AlphaLabel="$AlphaLabel" $BITBUCKET_CLONE_DIR/src/Dyndle.Modules.sln 
       artifacts:
        - build/packages/**
        - build/packages_no_conflict/**
    - step: &push-private
       name: Push all packages to private repository
       size: 2x
       script:
        - nuget sources add -Name privaterepo2 -Source $PRIVATE_REPO_REAL_URL -UserName $PRIVATE_REPO_REAL_USERNAME -Password $PRIVATE_REPO_REAL_PASSWORD
        - nuget push build/packages/Dyndle.Modules.Core*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Modules.Globalization*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Modules.ImageEnhancement*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Modules.Management*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Modules.Navigation*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Modules.Search*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Providers.Tridion91*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Providers.Tridion95*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Providers.Tridion10*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
        - nuget push build/packages/Dyndle.Quickstart.Web*.nupkg $PRIVATE_NUGET_APIKEY -Source privaterepo2
    - step: &push-public
       name: Push all packages to public repository
       size: 2x
       script:
        - nuget push build/packages/Dyndle.Modules.Core*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Modules.Globalization*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Modules.ImageEnhancement*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Modules.Management*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Modules.Navigation*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Modules.Search*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Providers.Tridion91*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Providers.Tridion95*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Providers.Tridion10*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
        - nuget push build/packages/Dyndle.Quickstart.Web*.nupkg $DYNDLE_PUBLIC_NUGET_APIKEY -Source https://api.nuget.org/v3/index.json
pipelines:
  branches:
    master:
        - step: *build-packages
        - step: *push-public
    develop:
        - step: *build-packages
        - step: *push-private
            