using System;
using System.Web.WebPages;
using Dyndle.Modules.Search.Contracts;
using Dyndle.Modules.Search.Extensions;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Search.Areas.Search.Views.Search
{
#line 1 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Search/Views/Search/FullResults.cshtml")]
    public partial class _Areas_Search_Views_Search_FullResults_cshtml : System.Web.Mvc.WebViewPage<ISearchResults>
    {
        public _Areas_Search_Views_Search_FullResults_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
 if (Model.Total > 0 && Model.Items != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <ul");

WriteLiteral(" style=\"list-style-type:none;margin:0;padding:0;\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
         foreach (var item in Model.Items)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" style=\"display: block; min-height:100px\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 309), Tuple.Create("\"", 340)
            
            #line 9 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
, Tuple.Create(Tuple.Create("", 315), Tuple.Create<System.Object, System.Int32>(item.ImageUrl.GetValue()
            
            #line default
            #line hidden
, 315), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" style=\"width: 100px; height: 100px; float:left;\"");

WriteLiteral("/>\r\n                <h3><a");

WriteAttribute("href", Tuple.Create(" href=\"", 423), Tuple.Create("\"", 451)
            
            #line 10 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
, Tuple.Create(Tuple.Create("", 430), Tuple.Create<System.Object, System.Int32>(item.Urls.GetValue()
            
            #line default
            #line hidden
, 430), false)
);

WriteLiteral(">");

            
            #line 10 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
                                               Write(item.Title.GetValue());

            
            #line default
            #line hidden
WriteLiteral("</a></h3>\r\n                <p>");

            
            #line 11 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
              Write(item.Summary.GetValue());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </li> \r\n");

            
            #line 13 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");

            
            #line 15 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
    Write(Model.ErrorMessage != null ? Model.ErrorMessage : "No more results");

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 21 "..\..\Areas\Search\Views\Search\FullResults.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
