using System;
using System.Web.WebPages;
using Dyndle.Modules.Search.Contracts;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Search.Areas.Search.Views.Search
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Search/Views/Search/ShortResults.cshtml")]
    public partial class _Areas_Search_Views_Search_ShortResults_cshtml : System.Web.Mvc.WebViewPage<ISearchResults>
    {
        public _Areas_Search_Views_Search_ShortResults_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
 if (Model.Total > 0)
{

            
            #line default
            #line hidden
WriteLiteral("<ul");

WriteLiteral(" style=\"list-style-type:none;margin:0;padding:0;\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
     foreach (var item in Model.Items)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 179), Tuple.Create("\"", 195)
            
            #line 8 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
, Tuple.Create(Tuple.Create("", 186), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 186), false)
);

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
                           Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a> \r\n        </li>\r\n");

            
            #line 10 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul> \r\n");

            
            #line 12 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
Write(Model.ErrorMessage != null ? Model.ErrorMessage : "No results found");

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

            
            #line 18 "..\..\Areas\Search\Views\Search\ShortResults.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
