using Dyndle.Modules.Core.Html;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dyndle.Modules.Feedback;
    
    #line 1 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
    using Dyndle.Modules.Feedback.Html;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
    using Dyndle.Modules.Feedback.ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Feedback/Views/Feedback/FeedbackForm.cshtml")]
    public partial class _Areas_Feedback_Views_Feedback_FeedbackForm_cshtml : System.Web.Mvc.WebViewPage<FeedbackFormViewModel>
    {
        public _Areas_Feedback_Views_Feedback_FeedbackForm_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"contact-form\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
     using (Html.BeginForm())
    {
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-8 col-md-offset-2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 14 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                   Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 18 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.DropDownListFor(m => m.Title, Html.CreateSelectList(Model.Titles, Html.GetLabel(FeedbackConstants.Labels.Title)), new { @class = "selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 771), Tuple.Create("\"", 802)
            
            #line 19 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 777), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Title)
            
            #line default
            #line hidden
, 777), false)
);

WriteLiteral(">");

            
            #line 19 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                              Write(Html.GetLabel(FeedbackConstants.Labels.Title));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 21 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.Name, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.Name) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1024), Tuple.Create("\"", 1054)
            
            #line 22 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 1030), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Name)
            
            #line default
            #line hidden
, 1030), false)
);

WriteLiteral(">");

            
            #line 22 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                             Write(Html.GetLabel(FeedbackConstants.Labels.Name));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 24 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.FirstName, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.FirstName) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1285), Tuple.Create("\"", 1320)
            
            #line 25 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 1291), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.FirstName)
            
            #line default
            #line hidden
, 1291), false)
);

WriteLiteral(">");

            
            #line 25 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                  Write(Html.GetLabel(FeedbackConstants.Labels.FirstName));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 27 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.Address, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.Address) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1552), Tuple.Create("\"", 1585)
            
            #line 28 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 1558), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Address)
            
            #line default
            #line hidden
, 1558), false)
);

WriteLiteral(">");

            
            #line 28 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                Write(Html.GetLabel(FeedbackConstants.Labels.Address));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 30 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.PostalCode, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.PostalCode) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1821), Tuple.Create("\"", 1857)
            
            #line 31 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 1827), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.PostalCode)
            
            #line default
            #line hidden
, 1827), false)
);

WriteLiteral(">");

            
            #line 31 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                   Write(Html.GetLabel(FeedbackConstants.Labels.PostalCode));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 33 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.City, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.City) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 2084), Tuple.Create("\"", 2114)
            
            #line 34 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 2090), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.City)
            
            #line default
            #line hidden
, 2090), false)
);

WriteLiteral(">");

            
            #line 34 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                             Write(Html.GetLabel(FeedbackConstants.Labels.City));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 36 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.Phone, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.Phone) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 2337), Tuple.Create("\"", 2368)
            
            #line 37 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 2343), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Phone)
            
            #line default
            #line hidden
, 2343), false)
);

WriteLiteral(">");

            
            #line 37 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                              Write(Html.GetLabel(FeedbackConstants.Labels.Phone));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.DropDownListFor(m => m.Country, Html.CreateSelectList(Model.Countries, Html.GetLabel(FeedbackConstants.Labels.Country)), new { @class = "selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 2739), Tuple.Create("\"", 2772)
            
            #line 41 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 2745), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Country)
            
            #line default
            #line hidden
, 2745), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                Write(Html.GetLabel(FeedbackConstants.Labels.Country));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 43 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.Email, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.Email) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 2998), Tuple.Create("\"", 3029)
            
            #line 44 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 3004), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Email)
            
            #line default
            #line hidden
, 3004), false)
);

WriteLiteral(">");

            
            #line 44 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                              Write(Html.GetLabel(FeedbackConstants.Labels.Email));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 46 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.ConfirmEmail, new { placeholder = Html.GetLabel(FeedbackConstants.Labels.ConfirmEmail) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 3267), Tuple.Create("\"", 3305)
            
            #line 47 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 3273), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.ConfirmEmail)
            
            #line default
            #line hidden
, 3273), false)
);

WriteLiteral(">");

            
            #line 47 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                     Write(Html.GetLabel(FeedbackConstants.Labels.ConfirmEmail));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.DropDownListFor(m => m.AgeRange, Html.CreateSelectList(Model.AgeRanges, Html.GetLabel(FeedbackConstants.Labels.AgeRange)), new { @class = "selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 3598), Tuple.Create("\"", 3632)
            
            #line 50 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 3604), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.AgeRange)
            
            #line default
            #line hidden
, 3604), false)
);

WriteLiteral(">");

            
            #line 50 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                 Write(Html.GetLabel(FeedbackConstants.Labels.AgeRange));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 52 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.DropDownListFor(m => m.AffectedProduct, Html.CreateSelectList(Model.Products, Html.GetLabel(FeedbackConstants.Labels.AffectedProduct)), new { @class = "selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 3933), Tuple.Create("\"", 3974)
            
            #line 53 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 3939), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.AffectedProduct)
            
            #line default
            #line hidden
, 3939), false)
);

WriteLiteral(">");

            
            #line 53 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                        Write(Html.GetLabel(FeedbackConstants.Labels.AffectedProduct));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.ControlNumber, new { placeholder = @Html.GetLabel(FeedbackConstants.Labels.ControlNumber) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 4225), Tuple.Create("\"", 4264)
            
            #line 56 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 4231), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.ControlNumber)
            
            #line default
            #line hidden
, 4231), false)
);

WriteLiteral(">");

            
            #line 56 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                      Write(Html.Raw(Html.GetLabel(FeedbackConstants.Labels.ControlNumberExplanation)));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextBoxFor(m => m.BarCode, new { placeholder = @Html.GetLabel(FeedbackConstants.Labels.BarCode) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 4521), Tuple.Create("\"", 4554)
            
            #line 59 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 4527), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.BarCode)
            
            #line default
            #line hidden
, 4527), false)
);

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                Write(Html.Raw(Html.GetLabel(FeedbackConstants.Labels.BarCodeExplanation)));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </div>\r\n                    </div>\r\n\r\n         " +
"           <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 65 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.DropDownListFor(m => m.Reason, Html.CreateSelectList(Model.Reasons, Html.GetLabel(FeedbackConstants.Labels.Reason)), new { @class = "selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 5013), Tuple.Create("\"", 5045)
            
            #line 66 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 5019), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.Reason)
            
            #line default
            #line hidden
, 5019), false)
);

WriteLiteral(">");

            
            #line 66 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                               Write(Html.GetLabel(FeedbackConstants.Labels.Reason));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n                        </div>\r\n                    </div>\r\n\r\n        " +
"            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 72 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                       Write(Html.TextAreaFor(m => m.Message, new { rows = "6", placeholder = @Html.GetLabel(FeedbackConstants.Labels.Message) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"row checkbox-input\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <input");

WriteAttribute("id", Tuple.Create(" id=\"", 5601), Tuple.Create("\"", 5647)
            
            #line 78 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 5606), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.AcceptTermsConditions)
            
            #line default
            #line hidden
, 5606), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 5648), Tuple.Create("\"", 5698)
            
            #line 78 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
        , Tuple.Create(Tuple.Create("", 5655), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.AcceptTermsConditions)
            
            #line default
            #line hidden
, 5655), false)
);

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" ");

            
            #line 78 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                                                                                                              Write(Model.AcceptTermsConditions ? "checked" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 5813), Tuple.Create("\"", 5860)
            
            #line 79 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 5819), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.AcceptTermsConditions)
            
            #line default
            #line hidden
, 5819), false)
);

WriteLiteral(">");

            
            #line 79 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                              Write(Html.Raw(Html.GetLabel(FeedbackConstants.Labels.TermsConditions)));

            
            #line default
            #line hidden
WriteLiteral("*</label>\r\n                            <input");

WriteAttribute("name", Tuple.Create(" name=\"", 5973), Tuple.Create("\"", 6023)
            
            #line 80 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 5980), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.AcceptTermsConditions)
            
            #line default
            #line hidden
, 5980), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"false\"");

WriteLiteral(">\r\n\r\n                            <input");

WriteAttribute("id", Tuple.Create(" id=\"", 6091), Tuple.Create("\"", 6131)
            
            #line 82 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 6096), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.NewsletterOptIn)
            
            #line default
            #line hidden
, 6096), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 6132), Tuple.Create("\"", 6176)
            
            #line 82 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
  , Tuple.Create(Tuple.Create("", 6139), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.NewsletterOptIn)
            
            #line default
            #line hidden
, 6139), false)
);

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" ");

            
            #line 82 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                                                                                                  Write(Model.NewsletterOptIn ? "checked" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 6285), Tuple.Create("\"", 6326)
            
            #line 83 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 6291), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m => m.NewsletterOptIn)
            
            #line default
            #line hidden
, 6291), false)
);

WriteLiteral(">");

            
            #line 83 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                        Write(Html.GetLabel(FeedbackConstants.Labels.SignedUpNewsletter));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <input");

WriteAttribute("name", Tuple.Create(" name=\"", 6431), Tuple.Create("\"", 6475)
            
            #line 84 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
, Tuple.Create(Tuple.Create("", 6438), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.NewsletterOptIn)
            
            #line default
            #line hidden
, 6438), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"false\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n\r\n                " +
"    <div");

WriteLiteral(" class=\"contact-form__actions\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-pink-outline\"");

WriteLiteral(">");

            
            #line 89 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
                                                                      Write(Html.GetLabel(FeedbackConstants.Labels.Send));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </div>\r\n\r\n                </div>\r\n            </di" +
"v>\r\n        </div>\r\n");

            
            #line 95 "..\..\Areas\Feedback\Views\Feedback\FeedbackForm.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
