using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Shared
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Management_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Management_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!doctype html>\r\n<html>\r\n<head>\r\n    <title>Cache</title>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"https://unpkg.com/purecss@1.0.0/build/pure-min.css\"");

WriteLiteral(" integrity=\"sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP" +
"9w\"");

WriteLiteral(" crossorigin=\"anonymous\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n\r\n    <style>\r\n        .sidebar {\r\n            background-color: darkgrey;\r\n  " +
"          padding: 10px;\r\n        }\r\n\r\n        .content {\r\n            padding: " +
"10px;\r\n        }\r\n    </style>\r\n</head>\r\n\r\n<body>\r\n    <div");

WriteLiteral(" id=\"layout\"");

WriteLiteral(" class=\"pure-g\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pure-u-1-24\"");

WriteLiteral(">\r\n\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"sidebar pure-u-1-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"brand-title\"");

WriteLiteral(">DD4T admin tools</h2>\r\n\r\n                <div");

WriteLiteral(" class=\"pure-menu\"");

WriteLiteral(">\r\n\r\n                    <ul");

WriteLiteral(" class=\"pure-menu-list\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"pure-menu-item pure-menu-selected\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" class=\"pure-menu-link\"");

WriteLiteral(" href=\"/admin/cache\"");

WriteLiteral(">Cache</a>\r\n                        </li>\r\n                    </ul>\r\n           " +
"     </div>\r\n\r\n\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"content pure-u-3-4\"");

WriteLiteral(">\r\n");

WriteLiteral("           ");

            
            #line 44 "..\..\Areas\Management\Views\Shared\_Layout.cshtml"
      Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"pure-u-1-24\"");

WriteLiteral(">\r\n\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
