using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Cache
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Cache/_ViewStart.cshtml")]
    public partial class _Areas_Management_Views_Cache__ViewStart_cshtml : System.Web.Mvc.ViewStartPage
    {
        public _Areas_Management_Views_Cache__ViewStart_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Management\Views\Cache\_ViewStart.cshtml"
  
    Layout = "~/Areas/Management/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
