using System;
using System.Web.WebPages;
using Dyndle.Modules.Core.Extensions;
using Dyndle.Modules.Management.Extensions;
using Dyndle.Modules.Management.Models;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Cache
{
#line 2 "..\..\Areas\Management\Views\Cache\List.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Cache/List.cshtml")]
    public partial class _Areas_Management_Views_Cache_List_cshtml : System.Web.Mvc.WebViewPage<CacheListInfo>
    {
        public _Areas_Management_Views_Cache_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h1>Cache</h1>\r\n<span>The cache contains ");

            
            #line 5 "..\..\Areas\Management\Views\Cache\List.cshtml"
                    Write(Model.Total);

            
            #line default
            #line hidden
WriteLiteral("</span> items.\r\n<form");

WriteLiteral(" class=\"pure-form\"");

WriteLiteral(" action=\"\"");

WriteLiteral(">\r\n    <fieldset>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteAttribute("value", Tuple.Create(" value=\"", 282), Tuple.Create("\"", 308)
            
            #line 8 "..\..\Areas\Management\Views\Cache\List.cshtml"
, Tuple.Create(Tuple.Create("", 290), Tuple.Create<System.Object, System.Int32>(Model.SearchQuery
            
            #line default
            #line hidden
, 290), false)
);

WriteLiteral(" placeholder=\"Search\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"pure-button\"");

WriteLiteral(">Search in the cache</button>\r\n        <button");

WriteLiteral(" onClick=\"window.location=\'/admin/cache/removeall\'; return false\"");

WriteLiteral(" class=\"pure-button pure-button-primary\"");

WriteLiteral(">Clear cache</button>\r\n    </fieldset>\r\n</form>\r\n\r\n");

            
            #line 14 "..\..\Areas\Management\Views\Cache\List.cshtml"
 if (Model.PaginationEnabled)
{

            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteLiteral(" class=\"pure-form\"");

WriteLiteral(" action=\"\"");

WriteLiteral(">\r\n        <fieldset>\r\n");

            
            #line 18 "..\..\Areas\Management\Views\Cache\List.cshtml"
            
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Management\Views\Cache\List.cshtml"
             foreach (var pageToShow in Model.PagesToShow)
            {
                var nrToShow = pageToShow + 1;
                if (pageToShow == -1) // -1 = show ellipsis
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"pure-button pure-button-disabled\"");

WriteLiteral(">...</button>\r\n");

            
            #line 24 "..\..\Areas\Management\Views\Cache\List.cshtml"
                    continue;
                }
                var searchQueryToAdd = Model.SearchQuery == null ? "" : Model.SearchQuery.UrlEncode();
                if (pageToShow == Model.CurrentPageNr)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"pure-button pure-button-disabled\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\Management\Views\Cache\List.cshtml"
                                                                Write(nrToShow);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 30 "..\..\Areas\Management\Views\Cache\List.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteAttribute("onClick", Tuple.Create(" onClick=\"", 1369), Tuple.Create("\"", 1471)
, Tuple.Create(Tuple.Create("", 1379), Tuple.Create("window.location=\'/admin/cache?pageNr=", 1379), true)
            
            #line 33 "..\..\Areas\Management\Views\Cache\List.cshtml"
, Tuple.Create(Tuple.Create("", 1416), Tuple.Create<System.Object, System.Int32>(pageToShow
            
            #line default
            #line hidden
, 1416), false)
, Tuple.Create(Tuple.Create("", 1427), Tuple.Create("&amp;search=", 1427), true)
            
            #line 33 "..\..\Areas\Management\Views\Cache\List.cshtml"
                 , Tuple.Create(Tuple.Create("", 1439), Tuple.Create<System.Object, System.Int32>(searchQueryToAdd
            
            #line default
            #line hidden
, 1439), false)
, Tuple.Create(Tuple.Create("", 1456), Tuple.Create("\';", 1456), true)
, Tuple.Create(Tuple.Create(" ", 1458), Tuple.Create("return", 1459), true)
, Tuple.Create(Tuple.Create(" ", 1465), Tuple.Create("false", 1466), true)
);

WriteLiteral(" class=\"pure-button\"");

WriteLiteral(">");

            
            #line 33 "..\..\Areas\Management\Views\Cache\List.cshtml"
                                                                                                                                                  Write(nrToShow);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 34 "..\..\Areas\Management\Views\Cache\List.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </fieldset>\r\n    </form>\r\n");

            
            #line 38 "..\..\Areas\Management\Views\Cache\List.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<table");

WriteLiteral(" class=\"pure-table pure-table-horizontal\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>Key</th>\r\n        <th>Value</th>\r\n        <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">Actions</th>\r\n    </tr>\r\n");

            
            #line 45 "..\..\Areas\Management\Views\Cache\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Management\Views\Cache\List.cshtml"
      
        var i = 0;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 48 "..\..\Areas\Management\Views\Cache\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Management\Views\Cache\List.cshtml"
     foreach (var item in Model.Items)
    {
        var cssClass = (++i % 2 == 1) ? @"class=""pure-table-odd""" : "";



            
            #line default
            #line hidden
WriteLiteral("        <tr ");

            
            #line 53 "..\..\Areas\Management\Views\Cache\List.cshtml"
       Write(cssClass);

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Areas\Management\Views\Cache\List.cshtml"
           Write(item.Key);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 58 "..\..\Areas\Management\Views\Cache\List.cshtml"
           Write(item.Value.ToString().Summarize());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2126), Tuple.Create("\"", 2177)
, Tuple.Create(Tuple.Create("", 2133), Tuple.Create("/admin/cache/remove/", 2133), true)
            
            #line 61 "..\..\Areas\Management\Views\Cache\List.cshtml"
, Tuple.Create(Tuple.Create("", 2153), Tuple.Create<System.Object, System.Int32>(item.Key.Base64Encode()
            
            #line default
            #line hidden
, 2153), false)
);

WriteLiteral(">Remove</a> |\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2211), Tuple.Create("\"", 2260)
, Tuple.Create(Tuple.Create("", 2218), Tuple.Create("/admin/cache/item/", 2218), true)
            
            #line 62 "..\..\Areas\Management\Views\Cache\List.cshtml"
, Tuple.Create(Tuple.Create("", 2236), Tuple.Create<System.Object, System.Int32>(item.Key.Base64Encode()
            
            #line default
            #line hidden
, 2236), false)
);

WriteLiteral(">View</a>\r\n            </td>\r\n        </tr>\r\n");

            
            #line 65 "..\..\Areas\Management\Views\Cache\List.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");

        }
    }
}
#pragma warning restore 1591
