using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Cache
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Cache/RemoveAll.cshtml")]
    public partial class _Areas_Management_Views_Cache_RemoveAll_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Management_Views_Cache_RemoveAll_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h1>Cache removal</h1>\r\nCache has been cleared. Click <a");

WriteLiteral(" href=\"/admin/cache\"");

WriteLiteral(">here</a> to return to the cache listing.\r\n");

        }
    }
}
#pragma warning restore 1591
