using System.Web.WebPages;
using Dyndle.Modules.Core.Extensions;
using Dyndle.Modules.Management.Models;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyndle.Modules.Management.Areas.Management.Views.Cache
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Management/Views/Cache/Remove.cshtml")]
    public partial class _Areas_Management_Views_Cache_Remove_cshtml : System.Web.Mvc.WebViewPage<CacheItem>
    {
        public _Areas_Management_Views_Cache_Remove_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h1>Cache removal</h1>\r\nItem with key ");

            
            #line 3 "..\..\Areas\Management\Views\Cache\Remove.cshtml"
         Write(Model.Key.Base64Decode());

            
            #line default
            #line hidden
WriteLiteral(" has been removed. Click <a");

WriteLiteral(" href=\"/admin/cache\"");

WriteLiteral(">here</a> to return to the cache listing.\r\n");

        }
    }
}
#pragma warning restore 1591
