#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Trivident.Modules.Navigation.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Navigation/Views/Navigation/Breadcrumb.cshtml")]
    public partial class _Areas_Navigation_Views_Navigation_Breadcrumb_cshtml : System.Web.Mvc.WebViewPage<ISitemapItem>
    {
        public _Areas_Navigation_Views_Navigation_Breadcrumb_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
 if (Model.Items != null && Model.Items.Count > 0)
{
    const int maxItems = 5;
    int start = Model.Items.Count > maxItems ? Model.Items.Count - (maxItems) + 1 : 1;


            
            #line default
            #line hidden
WriteLiteral("    <ol");

WriteLiteral(" class=\"navigation breadcrumb\"");

WriteLiteral(">\n        <li>\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 255), Tuple.Create("\"", 281)
            
            #line 9 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
, Tuple.Create(Tuple.Create("", 262), Tuple.Create<System.Object, System.Int32>(Model.Items[0].Url
            
            #line default
            #line hidden
, 262), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 9 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
                                                                                 Write(Model.Items[0].Title);

            
            #line default
            #line hidden
WriteLiteral("</span></i></a>\n        </li>\n");

            
            #line 11 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
         if (start > 1)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li>...</li>\n");

            
            #line 14 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 15 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
         for (int i = start; i < Model.Items.Count - 1; i++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 536), Tuple.Create("\"", 562)
            
            #line 17 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
, Tuple.Create(Tuple.Create("", 543), Tuple.Create<System.Object, System.Int32>(Model.Items[i].Url
            
            #line default
            #line hidden
, 543), false)
);

WriteLiteral(">");

            
            #line 17 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
                                         Write(Model.Items[i].Title);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\n");

            
            #line 18 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 19 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
         if (Model.Items.Count > 1)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 21 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
                          Write(Model.Items[Model.Items.Count - 1].Title);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 22 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ol>\n");

            
            #line 24 "..\..\Areas\Navigation\Views\Navigation\Breadcrumb.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
