#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Trivident.Modules.Navigation.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Navigation/Views/Navigation/LeftNavigation.cshtml")]
    public partial class _Areas_Navigation_Views_Navigation_LeftNavigation_cshtml : System.Web.Mvc.WebViewPage<ISitemapItem>
    {
        public _Areas_Navigation_Views_Navigation_LeftNavigation_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<nav>\n    <ul");

WriteLiteral(" class=\"navigation left\"");

WriteLiteral(">\n");

            
            #line 4 "..\..\Areas\Navigation\Views\Navigation\LeftNavigation.cshtml"
        
            
            #line default
            #line hidden
            
            #line 4 "..\..\Areas\Navigation\Views\Navigation\LeftNavigation.cshtml"
         foreach (var item in Model.Items)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 127), Tuple.Create("\"", 187)
            
            #line 6 "..\..\Areas\Navigation\Views\Navigation\LeftNavigation.cshtml"
, Tuple.Create(Tuple.Create("", 135), Tuple.Create<System.Object, System.Int32>(item.Url == Request.Url.LocalPath ? "active" : ""
            
            #line default
            #line hidden
, 135), false)
);

WriteLiteral(">\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 208), Tuple.Create("\"", 224)
            
            #line 7 "..\..\Areas\Navigation\Views\Navigation\LeftNavigation.cshtml"
, Tuple.Create(Tuple.Create("", 215), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 215), false)
);

WriteLiteral(">");

            
            #line 7 "..\..\Areas\Navigation\Views\Navigation\LeftNavigation.cshtml"
                               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n            </li>\n");

            
            #line 9 "..\..\Areas\Navigation\Views\Navigation\LeftNavigation.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\n</nav>");

        }
    }
}
#pragma warning restore 1591
