#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Trivident.Modules.Navigation.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Navigation/Views/Navigation/TopNavigation.cshtml")]
    public partial class _Areas_Navigation_Views_Navigation_TopNavigation_cshtml : System.Web.Mvc.WebViewPage<ISitemapItem>
    {
        public _Areas_Navigation_Views_Navigation_TopNavigation_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"navigation top\"");

WriteLiteral(">\n");

            
            #line 3 "..\..\Areas\Navigation\Views\Navigation\TopNavigation.cshtml"
    
            
            #line default
            #line hidden
            
            #line 3 "..\..\Areas\Navigation\Views\Navigation\TopNavigation.cshtml"
     foreach (var item in Model.Items)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteAttribute("class", Tuple.Create(" class=\"", 104), Tuple.Create("\"", 175)
            
            #line 5 "..\..\Areas\Navigation\Views\Navigation\TopNavigation.cshtml"
, Tuple.Create(Tuple.Create("", 112), Tuple.Create<System.Object, System.Int32>(Request.Url.LocalPath.StartsWith(item.Url) ? "active" : null
            
            #line default
            #line hidden
, 112), false)
);

WriteLiteral(">\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 192), Tuple.Create("\"", 208)
            
            #line 6 "..\..\Areas\Navigation\Views\Navigation\TopNavigation.cshtml"
, Tuple.Create(Tuple.Create("", 199), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 199), false)
);

WriteLiteral(">");

            
            #line 6 "..\..\Areas\Navigation\Views\Navigation\TopNavigation.cshtml"
                           Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n        </li>\n");

            
            #line 8 "..\..\Areas\Navigation\Views\Navigation\TopNavigation.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
