#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Trivident.Modules.Core.Html;
    using Trivident.Modules.Search;
    using Trivident.Modules.Search.Contracts;
    using Trivident.Modules.Search.Extensions;
    using Trivident.Modules.Search.Models;
    
    #line 1 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
    using Trivident.Modules.Search.Providers.Solr;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Search/Views/Search/SearchResults.cshtml")]
    public partial class _Areas_Search_Views_Search_SearchResults_cshtml : System.Web.Mvc.WebViewPage<ISearchResults>
    {
        public _Areas_Search_Views_Search_SearchResults_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
  
    var baseUrl = Request.Url.LocalPath + "?";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>Search Results</h1>\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 170), Tuple.Create("\"", 187)
            
            #line 7 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 179), Tuple.Create<System.Object, System.Int32>(baseUrl
            
            #line default
            #line hidden
, 179), false)
);

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"q\"");

WriteLiteral(" class=\"field-input\"");

WriteAttribute("value", Tuple.Create(" value=\"", 242), Tuple.Create("\"", 272)
            
            #line 8 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 250), Tuple.Create<System.Object, System.Int32>(Model.Query.QueryText
            
            #line default
            #line hidden
, 250), false)
);

WriteLiteral("/>\r\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(" />\r\n    <br/>\r\n");

            
            #line 11 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
     if (Model.Total > 0)
    { 

            
            #line default
            #line hidden
WriteLiteral("        <h2>\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
       Write(String.Format("Showing {0}-{1} of {2} results", Model.Query.Start, Model.End, Model.Total));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </h2>\r\n");

WriteLiteral("        <br/>\r\n");

WriteLiteral("        <ul");

WriteLiteral(" style=\"list-style-type: none;margin:0;padding:0;\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" style=\"display: inline; padding:5px; margin:5px; border:1px #808080 solid;backgr" +
"ound-color:lightblue\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 718), Tuple.Create("\"", 796)
            
            #line 19 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 725), Tuple.Create<System.Object, System.Int32>(baseUrl + SearchProvider.GetFilterQueryString(Model.Query,null,null)
            
            #line default
            #line hidden
, 725), false)
);

WriteLiteral(">Clear Filters</a>\r\n            </li>\r\n            ");

WriteLiteral("\r\n        </ul>\r\n");

WriteLiteral("        <br/>\r\n");

            
            #line 29 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
   Write(Html.Partial("FullResults"));

            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
                                    
        if (Model.Total > Model.Query.PageSize)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n            Page: \r\n");

            
            #line 34 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
            
            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
             if (Model.Query.Start > 1)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1484), Tuple.Create("\"", 1573)
            
            #line 36 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 1491), Tuple.Create<System.Object, System.Int32>(baseUrl + SearchProvider.GetPageQueryString(Model.Query, Model.CurrentPage - 1)
            
            #line default
            #line hidden
, 1491), false)
);

WriteLiteral(">");

            
            #line 36 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
                                                                                                         Write(Model.CurrentPage - 1);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 37 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <strong>");

            
            #line 38 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
               Write(Model.CurrentPage);

            
            #line default
            #line hidden
WriteLiteral(" </strong>\r\n");

            
            #line 39 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
             if (Model.HasMore)
            {

            
            #line default
            #line hidden
WriteLiteral("              <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1734), Tuple.Create("\"", 1823)
            
            #line 41 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 1741), Tuple.Create<System.Object, System.Int32>(baseUrl + SearchProvider.GetPageQueryString(Model.Query, Model.CurrentPage + 1)
            
            #line default
            #line hidden
, 1741), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
                                                                                                       Write(Model.CurrentPage + 1);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 42 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 44 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
        }
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 49 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
    Write(Model.ErrorMessage != null ? Model.ErrorMessage : "No results found");

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 51 "..\..\Areas\Search\Views\Search\SearchResults.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</form>");

        }
    }
}
#pragma warning restore 1591
