//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trivident.Modules.Feedback.Coheris {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gp-europe.net/webconsoplus/", ConfigurationName="Coheris.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Parameter 'trancheAge' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/addContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.addContactResponse addContact(Trivident.Modules.Feedback.Coheris.addContactRequest request);
        
        // CODEGEN: Parameter 'trancheAge' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/addContactPHP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.addContactPHPResponse addContactPHP(Trivident.Modules.Feedback.Coheris.addContactPHPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/GetCivilite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.CleValeur[] GetCivilite();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/GetPays", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.CleValeurStr[] GetPays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/GetMotifDeContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.CleValeur[] GetMotifDeContact();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/GetTrancheDAge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.CleValeur[] GetTrancheDAge();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/GetTrancheDAgeB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.CleValeur[] GetTrancheDAgeB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gp-europe.net/webconsoplus/GetProduitBySite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trivident.Modules.Feedback.Coheris.CleValeur[] GetProduitBySite(int siteDeProvenance);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addContact", WrapperNamespace="http://gp-europe.net/webconsoplus/", IsWrapped=true)]
    public partial class addContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=0)]
        public int civilite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=1)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=2)]
        public string prenom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=3)]
        public string adresse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=4)]
        public string ville;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=5)]
        public string codepostal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=6)]
        public string tel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=7)]
        public string pays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=8)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> trancheAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=10)]
        public int produitConcerne;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=11)]
        public string numControle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> numCodeBArre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=13)]
        public string remarque;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=14)]
        public int motifDeContact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=15)]
        public int siteDeProvenance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=16)]
        public bool optin;
        
        public addContactRequest() {
        }
        
        public addContactRequest(
                    int civilite, 
                    string nom, 
                    string prenom, 
                    string adresse, 
                    string ville, 
                    string codepostal, 
                    string tel, 
                    string pays, 
                    string email, 
                    System.Nullable<int> trancheAge, 
                    int produitConcerne, 
                    string numControle, 
                    System.Nullable<long> numCodeBArre, 
                    string remarque, 
                    int motifDeContact, 
                    int siteDeProvenance, 
                    bool optin) {
            this.civilite = civilite;
            this.nom = nom;
            this.prenom = prenom;
            this.adresse = adresse;
            this.ville = ville;
            this.codepostal = codepostal;
            this.tel = tel;
            this.pays = pays;
            this.email = email;
            this.trancheAge = trancheAge;
            this.produitConcerne = produitConcerne;
            this.numControle = numControle;
            this.numCodeBArre = numCodeBArre;
            this.remarque = remarque;
            this.motifDeContact = motifDeContact;
            this.siteDeProvenance = siteDeProvenance;
            this.optin = optin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addContactResponse", WrapperNamespace="http://gp-europe.net/webconsoplus/", IsWrapped=true)]
    public partial class addContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=0)]
        public string addContactResult;
        
        public addContactResponse() {
        }
        
        public addContactResponse(string addContactResult) {
            this.addContactResult = addContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addContactPHP", WrapperNamespace="http://gp-europe.net/webconsoplus/", IsWrapped=true)]
    public partial class addContactPHPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=0)]
        public int civilite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=1)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=2)]
        public string prenom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=3)]
        public string adresse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=4)]
        public string ville;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=5)]
        public string codepostal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=6)]
        public string tel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=7)]
        public string pays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=8)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> trancheAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=10)]
        public int produitConcerne;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=11)]
        public string numControle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=12)]
        public string numCodeBArre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=13)]
        public string remarque;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=14)]
        public int motifDeContact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=15)]
        public int siteDeProvenance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=16)]
        public bool optin;
        
        public addContactPHPRequest() {
        }
        
        public addContactPHPRequest(
                    int civilite, 
                    string nom, 
                    string prenom, 
                    string adresse, 
                    string ville, 
                    string codepostal, 
                    string tel, 
                    string pays, 
                    string email, 
                    System.Nullable<int> trancheAge, 
                    int produitConcerne, 
                    string numControle, 
                    string numCodeBArre, 
                    string remarque, 
                    int motifDeContact, 
                    int siteDeProvenance, 
                    bool optin) {
            this.civilite = civilite;
            this.nom = nom;
            this.prenom = prenom;
            this.adresse = adresse;
            this.ville = ville;
            this.codepostal = codepostal;
            this.tel = tel;
            this.pays = pays;
            this.email = email;
            this.trancheAge = trancheAge;
            this.produitConcerne = produitConcerne;
            this.numControle = numControle;
            this.numCodeBArre = numCodeBArre;
            this.remarque = remarque;
            this.motifDeContact = motifDeContact;
            this.siteDeProvenance = siteDeProvenance;
            this.optin = optin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addContactPHPResponse", WrapperNamespace="http://gp-europe.net/webconsoplus/", IsWrapped=true)]
    public partial class addContactPHPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gp-europe.net/webconsoplus/", Order=0)]
        public string addContactPHPResult;
        
        public addContactPHPResponse() {
        }
        
        public addContactPHPResponse(string addContactPHPResult) {
            this.addContactPHPResult = addContactPHPResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gp-europe.net/webconsoplus/")]
    public partial class CleValeur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cleField;
        
        private string valeurField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int cle {
            get {
                return this.cleField;
            }
            set {
                this.cleField = value;
                this.RaisePropertyChanged("cle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valeur {
            get {
                return this.valeurField;
            }
            set {
                this.valeurField = value;
                this.RaisePropertyChanged("valeur");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gp-europe.net/webconsoplus/")]
    public partial class CleValeurStr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cleField;
        
        private string valeurField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cle {
            get {
                return this.cleField;
            }
            set {
                this.cleField = value;
                this.RaisePropertyChanged("cle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valeur {
            get {
                return this.valeurField;
            }
            set {
                this.valeurField = value;
                this.RaisePropertyChanged("valeur");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Trivident.Modules.Feedback.Coheris.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Trivident.Modules.Feedback.Coheris.ServiceSoap>, Trivident.Modules.Feedback.Coheris.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trivident.Modules.Feedback.Coheris.addContactResponse Trivident.Modules.Feedback.Coheris.ServiceSoap.addContact(Trivident.Modules.Feedback.Coheris.addContactRequest request) {
            return base.Channel.addContact(request);
        }
        
        public string addContact(
                    int civilite, 
                    string nom, 
                    string prenom, 
                    string adresse, 
                    string ville, 
                    string codepostal, 
                    string tel, 
                    string pays, 
                    string email, 
                    System.Nullable<int> trancheAge, 
                    int produitConcerne, 
                    string numControle, 
                    System.Nullable<long> numCodeBArre, 
                    string remarque, 
                    int motifDeContact, 
                    int siteDeProvenance, 
                    bool optin) {
            Trivident.Modules.Feedback.Coheris.addContactRequest inValue = new Trivident.Modules.Feedback.Coheris.addContactRequest();
            inValue.civilite = civilite;
            inValue.nom = nom;
            inValue.prenom = prenom;
            inValue.adresse = adresse;
            inValue.ville = ville;
            inValue.codepostal = codepostal;
            inValue.tel = tel;
            inValue.pays = pays;
            inValue.email = email;
            inValue.trancheAge = trancheAge;
            inValue.produitConcerne = produitConcerne;
            inValue.numControle = numControle;
            inValue.numCodeBArre = numCodeBArre;
            inValue.remarque = remarque;
            inValue.motifDeContact = motifDeContact;
            inValue.siteDeProvenance = siteDeProvenance;
            inValue.optin = optin;
            Trivident.Modules.Feedback.Coheris.addContactResponse retVal = ((Trivident.Modules.Feedback.Coheris.ServiceSoap)(this)).addContact(inValue);
            return retVal.addContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trivident.Modules.Feedback.Coheris.addContactPHPResponse Trivident.Modules.Feedback.Coheris.ServiceSoap.addContactPHP(Trivident.Modules.Feedback.Coheris.addContactPHPRequest request) {
            return base.Channel.addContactPHP(request);
        }
        
        public string addContactPHP(
                    int civilite, 
                    string nom, 
                    string prenom, 
                    string adresse, 
                    string ville, 
                    string codepostal, 
                    string tel, 
                    string pays, 
                    string email, 
                    System.Nullable<int> trancheAge, 
                    int produitConcerne, 
                    string numControle, 
                    string numCodeBArre, 
                    string remarque, 
                    int motifDeContact, 
                    int siteDeProvenance, 
                    bool optin) {
            Trivident.Modules.Feedback.Coheris.addContactPHPRequest inValue = new Trivident.Modules.Feedback.Coheris.addContactPHPRequest();
            inValue.civilite = civilite;
            inValue.nom = nom;
            inValue.prenom = prenom;
            inValue.adresse = adresse;
            inValue.ville = ville;
            inValue.codepostal = codepostal;
            inValue.tel = tel;
            inValue.pays = pays;
            inValue.email = email;
            inValue.trancheAge = trancheAge;
            inValue.produitConcerne = produitConcerne;
            inValue.numControle = numControle;
            inValue.numCodeBArre = numCodeBArre;
            inValue.remarque = remarque;
            inValue.motifDeContact = motifDeContact;
            inValue.siteDeProvenance = siteDeProvenance;
            inValue.optin = optin;
            Trivident.Modules.Feedback.Coheris.addContactPHPResponse retVal = ((Trivident.Modules.Feedback.Coheris.ServiceSoap)(this)).addContactPHP(inValue);
            return retVal.addContactPHPResult;
        }
        
        public Trivident.Modules.Feedback.Coheris.CleValeur[] GetCivilite() {
            return base.Channel.GetCivilite();
        }
        
        public Trivident.Modules.Feedback.Coheris.CleValeurStr[] GetPays() {
            return base.Channel.GetPays();
        }
        
        public Trivident.Modules.Feedback.Coheris.CleValeur[] GetMotifDeContact() {
            return base.Channel.GetMotifDeContact();
        }
        
        public Trivident.Modules.Feedback.Coheris.CleValeur[] GetTrancheDAge() {
            return base.Channel.GetTrancheDAge();
        }
        
        public Trivident.Modules.Feedback.Coheris.CleValeur[] GetTrancheDAgeB() {
            return base.Channel.GetTrancheDAgeB();
        }
        
        public Trivident.Modules.Feedback.Coheris.CleValeur[] GetProduitBySite(int siteDeProvenance) {
            return base.Channel.GetProduitBySite(siteDeProvenance);
        }
    }
}
