#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Trivident.Modules.Management.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Management/Views/Shared/DisplayTemplates/ComponentPresentation.cshtml")]
    public partial class _Areas_Management_Views_Shared_DisplayTemplates_ComponentPresentation_cshtml_ : System.Web.Mvc.WebViewPage<DD4T.ContentModel.ComponentPresentation>
    {
        public _Areas_Management_Views_Shared_DisplayTemplates_ComponentPresentation_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<tr>\r\n    <td>Component ID</td>\r\n    <td>");

            
            #line 5 "..\..\Areas\Management\Views\Shared\DisplayTemplates\ComponentPresentation.cshtml"
   Write(Model.Component.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Component Title</td>\r\n    <td>");

            
            #line 9 "..\..\Areas\Management\Views\Shared\DisplayTemplates\ComponentPresentation.cshtml"
   Write(Model.Component.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Schema</td>\r\n    <td>");

            
            #line 13 "..\..\Areas\Management\Views\Shared\DisplayTemplates\ComponentPresentation.cshtml"
   Write(Model.Component.Schema.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Component Template ID</td>\r\n    <td>");

            
            #line 17 "..\..\Areas\Management\Views\Shared\DisplayTemplates\ComponentPresentation.cshtml"
   Write(Model.ComponentTemplate.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n<tr>\r\n    <td>Component Template Title</td>\r\n    <td>");

            
            #line 21 "..\..\Areas\Management\Views\Shared\DisplayTemplates\ComponentPresentation.cshtml"
   Write(Model.ComponentTemplate.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n</tr>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
