#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Trivident.Modules.Management.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Management/Views/Shared/DisplayTemplates/Listofstring.cshtml")]
    public partial class _Areas_Management_Views_Shared_DisplayTemplates_Listofstring_cshtml_ : System.Web.Mvc.WebViewPage<List<string>>
    {
        public _Areas_Management_Views_Shared_DisplayTemplates_Listofstring_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<tr>\r\n    <td>Value</td>\r\n    <td>\r\n        <ul>\r\n");

            
            #line 6 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
             foreach (var v in Model)
            {
                if ((bool)ViewData["isDependencyList"])
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 227), Tuple.Create("\"", 269)
, Tuple.Create(Tuple.Create("", 234), Tuple.Create("/admin/cache/item/", 234), true)
            
            #line 10 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
, Tuple.Create(Tuple.Create("", 252), Tuple.Create<System.Object, System.Int32>(v.Base64Encode()
            
            #line default
            #line hidden
, 252), false)
);

WriteLiteral(">");

            
            #line 10 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
                                                                 Write(v);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 11 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>");

            
            #line 14 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
                   Write(v);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 15 "..\..\Areas\Management\Views\Shared\DisplayTemplates\Listofstring.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </td>\r\n</tr>\r\n");

        }
    }
}
#pragma warning restore 1591
